### ISSUE TITLE
Nginx stub status config

### ISSUE THREAD

**Issue by hugronaphor** [instana/nginx-tracing#16]
Not sure where would I open the issue so doing it here.

In your docs you give an example of how to setup the [status location](https://github.com/instana/nginx-tracing/blob/02f47e5d347cd42a76b69723520826d2f8ec30f7/nginx/nginx.conf#L23) which would be accessible to anyone.

In https://github.com/instana/nginx-tracing/blob/02f47e5d347cd42a76b69723520826d2f8ec30f7/nginx/nginx.conf#L23
you're mentioning `allow all;    # don't ever push in production something like this :-)`.

I tried to do smth like:
```
        location /nginxst {
            stub_status on;
            allow 127.0.0.1;
            deny all;
            access_log off;
        }
```
But with this, Instana has no access to the stats.
Can you clarify how correctly to setup it or is it not intended to be used in production at all?

Thanks

**Comment by mmanciop** [comment]
Hi @hugronaphor,

It honestly depends on _where_ you deploy the Instana host agent and the Nginx process. My guess is that you are on a containerised platform, in which case `allow 127.0.0.1` works only from within the container or pod. Instead, it must be set to the IP that the Instana agent pod has.

We should move this discussion to a ticket on http://support.instana.com/ :-)

**Comment by hugronaphor** [comment]
It's indeed on a containerised platform.
Makes sense and thanks for feedback.
